BankALM/Models/Account.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BankALM.Models
{
    public class Account
    {
        public int AccountNumber { get; set; }
        public int CustomerId { get; set; }
        public decimal Balance { get; set; }

        public void Transfer(bool from, decimal amount)
        {
            if(from)
            {
                Balance -= amount;
            } else
            {
                Balance += amount;
            }
        }
    }
}

BankALM/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BankALM.Models
{
    public class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public List<Account> Accounts { get; set; } = new List<Account>();
    }
}

BankALM/ViewModels/TransactionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BankALM.ViewModels
{
    public class TransactionViewModel
    {
        public int From { get; set; }
        public int To { get; set; }
        public int Amount { get; set; }
        public string Message { get; set; }
    }
}

BankALM/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BankALM.Repo;
using Microsoft.AspNetCore.Mvc;

namespace BankALM.Controllers
{
    public class HomeController : Controller
    {
        private readonly BankRepository _bankContext;
         
        public HomeController(BankRepository bankContext)
        {
            _bankContext = bankContext;
        }
        public IActionResult Index()
        {
            var model = _bankContext.BankCustomers;
            return View(model);
        }
    }
}

BankALM/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BankALM.Repo;
using BankALM.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BankALM.Controllers
{
    public class TransactionController : Controller
    {
        private readonly BankRepository _bankContext;

        public TransactionController(BankRepository bankContext)
        {
            _bankContext = bankContext;
        }
        public IActionResult Index()
        {
            return View(new TransactionViewModel());
        }

        public IActionResult Withdraw(TransactionViewModel vm)
        {
            vm.From = vm.To;
            var res = _bankContext.Withdraw(vm);
            ViewData["Message"] = vm.Message;
            return View("Index",new TransactionViewModel());
        }
        public IActionResult Deposit(TransactionViewModel vm)
        {
            var res = _bankContext.Deposit(vm);
            ViewData["Message"] = vm.Message;
            return View("Index", new TransactionViewModel());
        }
    }
}

BankALM/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BankALM.Repo;
using BankALM.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BankALM.Controllers
{
    public class TransferController : Controller
    {
        private readonly BankRepository bankContext;

        public TransferController(BankRepository bankContext)
        {
            this.bankContext = bankContext;
        }

        public IActionResult Index()
        {
            return View(new TransactionViewModel());
        }

        public IActionResult Transfer(TransactionViewModel vm)
        {
            bankContext.Transfer(vm);
            ViewData["Message"] = vm.Message;
            return View("Index", new TransactionViewModel());
        }
    }
}

BankALM/Views/Home/Index.cshtml
@model List<BankALM.Models.Customer>
@{
    ViewData["Title"] = "Index";
}


<table>
    <thead>
    <tr>
        <th scope="col">Customers</th>
        <th scope="col">Accounts</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr >
            <td style="border: 1px solid black;">@item.CustomerId @item.CustomerName</td>
            <td style="border: 1px solid black;">
                @foreach (var account in item.Accounts)
                {
                    @account.AccountNumber<text>:&nbsp;</text>@account.Balance<text> SEK </text>
                    if (account != item.Accounts.Last())
                    {
                       <text><br/> </text>
                    }                
                }
            </td>
        </tr>
    }
    </tbody>
</table>

BankALM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <h2>Utterns Bank</h2>
    <hr />
    <a href="@Url.Action("Index","Home")"> Start </a>&nbsp;&nbsp;&nbsp;
    <a href="@Url.Action("Index","Transaction")">Transactions</a>&nbsp;&nbsp;&nbsp;
    <a href="@Url.Action("Index","Transfer")">Transfers</a>&nbsp;&nbsp;&nbsp;
    <hr />
    <div>
        @RenderBody()
    </div>
</body>
</html>

BankALM/Views/Transaction/Index.cshtml
@model BankALM.ViewModels.TransactionViewModel
@{
    ViewData["Title"] = "Index";
}
<script>
    window.onload = function() {
        @if (ViewData["Message"] != null && !string.IsNullOrWhiteSpace(ViewData["Message"].ToString()))
        {
            <text>
                alert('@ViewData["Message"]');
            </text>
        }
    }
</script>

<form asp-controller="Transaction">
    <label>Account Number</label><br />
    <input type="text" asp-for="To" placeholder="Enter number here" value=""/><br /><br />
    <label>Amount</label><br/>
    <input asp-for="Amount" type="number" placeholder="Amount" value="" min="1"/>

    <input type="submit" asp-action="Withdraw" value="Withdraw" />
    <input type="submit" asp-action="Deposit" value="Deposit" />
</form>

BankALM/Views/Transfer/Index.cshtml
@model BankALM.ViewModels.TransactionViewModel

@{
    ViewData["Title"] = "Index";
}

<script>
    window.onload = function() {
        @if (ViewData["Message"] != null && !string.IsNullOrWhiteSpace(ViewData["Message"].ToString()))
        {
            <text>
                alert('@ViewData["Message"]');
            </text>
        }
    }
</script>

<form asp-controller="Transaction">
    <label>Account Number</label><br />
    <input type="text" asp-for="From" placeholder="From" value="" /><br /><br />
    <input type="text" asp-for="To" placeholder="To" value="" /><br /><br />
    <label>Amount</label><br />
    <input asp-for="Amount" type="number" placeholder="Amount" value="" min="1" />

    <input type="submit" asp-action="Transfer" value="Transfer" />
</form>